### PR TITLE
Adding the re-certification functionality

### PR DESCRIPTION
**Pull request by thinkberg**

### CODE REVIEW

**Comment by oliver-steinbrecher** [comment]
@thinkberg How are you going to process the authentication ? Regarding the spec you're not leveraging the authorization header

**Comment by thinkberg** [comment]
The certificate signature will be employee for that. A token would be basically public in any of the apps used.

**Comment by mlenkeit** [comment]
We would suggest making the following changes:

- the re-issue API should be capable of receiving multiple certificates as input, not just one.

    This is required to reliably re-issue certificates.

- the re-issue API should be capable of returning multiple certificates as output, not just a one.

    This will make the API ready for future use cases and doesn't really hurt at the moment.

- the re-issue API should indicate to the client the relation between received and returned certificates.

    For example, a returned certificate might _replace_ one or multiple received certificates because of new vaccination series encoding. Or a returned certificate might in the future _extend_ a received certificate (same content, extended technical expiration date).

    It's the responsibility of the client to decide how to interpret this metadata.

This could look something like this:

```diff
       requestBody:
         description: A valid Digital Green Certificate (DGC) signed in Germany (DE).
         content:
-          application/cbor:
-            schema:
-              $ref: 'dcc-certify-api.yaml#/components/schemas/CertificateBinary'
-          application/cbor+base45:
-            schema:
-              $ref: 'dcc-certify-api.yaml#/components/schemas/CertificateEncoded'
+          application/json:
+            schema:
+              type: array
+              items:
+                $ref: 'dcc-certify-api.yaml#/components/schemas/CertificateEncoded'
       responses:
         '200':
           description: OK
           content:
-            application/cbor+base45:
-              schema:
-                $ref: 'dcc-certify-api.yaml#/components/schemas/CertificateEncoded'
-            application/cbor:
-              schema:
-                $ref: 'dcc-certify-api.yaml#/components/schemas/CertificateBinary'
+            application/json:
+              schema:
+                type: array
+                items:
+                  type: object
+                  properties:
+                    certificate:
+                      $ref: 'dcc-certify-api.yaml#/components/schemas/CertificateEncoded'
+                    relations:
+                      type: array
+                      items:
+                        type: object
+                        properties:
+                          certificate:
+                            $ref: 'dcc-certify-api.yaml#/components/schemas/CertificateEncoded'
+                          type:
+                            type: string
+                            enum:
+                              - tbd
```

Regarding authentication: we agree with the proposal from @thinkberg. A valid signature is the only reliably authentication check for such a public API. Additionally, the API should check that the certificate was signed with a German DSC (and not just check the `iat` claim of the CWT or the `co` attribute of the DCC).

/fyi @oliver-steinbrecher

**Comment by thinkberg** [comment]
Will take the suggestions into account. Also, yes, the certificate signature check will be valid only for German issues certificates.

**Comment by mlenkeit** [comment]
@thinkberg the latest changes on the request body make sense for us.

For the response body, we still have a slightly different understanding.

Let's take the following examples: 

- a request to _combine_ VC-1 (Janssen) and RC-1 could return a new VC-1', but it does not replace with VC-1 and RC-1 but only VC-1.
- a request to _renew_ VC-2 and RC-2 could return a new VC-2' and RC-2', whereas each replaces the respective input certificate

So on the response, the `type` should be on the certificate level and not on the response level. And it would required a relation to the input certificates.

**Comment by mlenkeit** [comment]
@thinkberg did you have a chance to review our recent comments?

**Comment by thinkberg** [comment]
Yes, I modeled it after the initial comment. However, I changed the relational response to an index in the request certificate list, so we don't send the certificates back and forth.

**Comment by vaubaehn** [comment]
> The certificate signature will be employed for that. A token would be basically public in any of the apps used.
> […](#)
> On 24. Jan 2022, at 09:43, oliver-steinbrecher ***@***.***> wrote: ﻿ @thinkberg How are you going to process the authentication ? Regarding the spec you're not leveraging the authorization header — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

@thinkberg 
Will there be a higher risk of (D)DoS-ing the public endpoint? Despite the authorization requests from Telematik or vaccination centers, now the requests for re-certification are 'going through' directly, and they may contain multiple DCCs what might increase the size of a single request by a lot.
Will the endpoint be able to handle such conditions?

**Comment by thinkberg** [comment]
Of course there is a risk of DDOSing the re-issue endpoint. However, we will ensure it does checks before hitting the secure certification API.

**Comment by thinkberg** [comment]
I am going to merge this PR now as we are now starting to develop this.

**Comment by thinkberg** [comment]
One last thing, I am going to rename the endpoint names from re-certify to reissue.

**Comment by vaubaehn** [comment]
> However, we will ensure it does checks before hitting the secure certification API.

@thinkberg Thanks for the clarification!
And thanks for your great work in all, btw.

**Comment by Ein-Tim** [comment]
Could the reissue API be misused to reissue the certificates from a user without their consent (e.g. vaccination protection is considered to only be valid for 180 days due to a new law from politics. Is it possible that than, as soon as the new law comes into effect, all Wallet apps contact the reissue API to get a new certificate with the new 180 days hardcoded in it?)?

**Comment by Ein-Tim** [comment]
Will somebody address https://github.com/Digitaler-Impfnachweis/certification-apis/pull/219#issuecomment-1035935112 or should I open a new issue?

**Comment by Ein-Tim** [comment]
@thinkberg Thank you!

**Pull request merged**
